version: "3"
services:

  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      SERVER_PORT: 3001
      DATABASE_URL: "postgresql://postgres:SebA661802.@postgres:5432/ragnaroktop?schema=public"
      FORCE_SEEDER: "false"
      SALT_HASH_PASSWORD: 15
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    ports:
      - 8080:3001
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    entrypoint: redis-server --appendonly yes

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=SebA661802.
    ports:
      - '5432:5432'

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    ports:
      - '7070:8081'
